### ISSUE TITLE
Add CodeClimate Maintainability badge

### ISSUE THREAD

**Issue by spritle** [spritlesoftware/chargebee-rails-subscriptions#14]
`[![Maintainability](https://api.codeclimate.com/v1/badges/2f9b7a79d17605b51f5e/maintainability)](https://codeclimate.com/github/spritlesoftware/chargebee-rails-subscriptions/maintainability)`

**Comment by spritle** [comment]
@sai92messy

**Comment by Thirumal-Sakthivel** [comment]
@spritle  Added CodeClimate Maintainability badge. :+1:
