### ISSUE TITLE
Rails 5.2 Support?

### ISSUE THREAD

**Issue by philipbjorge** [spritlesoftware/chargebee-rails-subscriptions#16]
What's the status of this project?
Will it be updated to support Rails 5.2? If work is done to support it, will it be merged? Will it be released?
Does this project have a maintainer?

Migrations do not currently run with Rails 5.2 out of the box
```
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateSubscriptions < ActiveRecord::Migration[4.2]
```

**Comment by sai92messy** [comment]
Hi @philipbjorge ,

We have currently merged a few PR related to rails 5+ support #9 and will be releasing the updates, once the remaining PRs are merged.
You are welcome to raise a PR to address this issue.
