### ISSUE TITLE
Description field of Plan

### ISSUE THREAD

**Issue by paulleoniuk** [spritlesoftware/chargebee-rails-subscriptions#6]
At the moment
``` ruby
    sync_plans.rake
``` 
task is not returning description of subscription plan. It have to be useful to use this field with rendering list of subscription plans.

**Comment by paulleoniuk** [comment]
#5

**Comment by sai92messy** [comment]
Sure, please go ahead and PR the update.

**Comment by Thirumal-Sakthivel** [comment]
@paulleoniuk We will close this issue once we merge the PR.

**Comment by sai92messy** [comment]
#5 is now merged, so closing this issue now.
