### ISSUE TITLE
Rake sync_plans

### ISSUE THREAD

**Issue by paulleoniuk** [spritlesoftware/chargebee-rails-subscriptions#7]
Why we need to input "y" when trying to sync subscription plans?

**Comment by sai92messy** [comment]
@paulleoniuk I think we don't need the user confirmation for this, since the user knows what he is upto with the rake task explaining it as well, Please raise a PR if interested.

**Comment by sai92messy** [comment]
This is now addressed in #11 , so closing this issue now.
